Add some crappy syles, project run history with jquery slides

diff --git a/minion b/minion
--- a/minion
+++ b/minion
@@ -1,1 +1,28 @@
-modules/minion-core/minion
+#!/bin/bash
+# 
+# Usage: ./minion [task:name] [--option1=optval1 --option2=optval2]
+#
+# And so on.
+#
+# To get help, pass in --help
+#
+# # Minion general help
+# ./minion --help
+# ./minion
+#
+# # Task specific help
+# ./minion task:name --help
+#
+
+if [[ $# > 0 && $1 != --* ]]
+then
+	TASK="--task=$1"
+	shift 1
+fi
+
+cd docroot
+
+php index.php --uri=minion "$TASK" "$@"
+
+# Pass the exit code back out
+exit $?
